fix compile

diff --git a/dev/check-sql-and-connect-mima b/dev/check-sql-and-connect-mima
--- a/dev/check-sql-and-connect-mima
+++ b/dev/check-sql-and-connect-mima
@@ -25,21 +25,19 @@ SPARK_HOME="$(cd "`dirname "$0"`"/..; pwd)"
 cd "$SPARK_HOME"
 
 TOOLS_CLASSPATH="$(build/sbt -DcopyDependencies=false "export tools/fullClasspath" | grep jar | tail -n1)"
-#SQL_BUILD_RESULT="$(build/sbt clean sql/package | tail -n1 | awk '{print $1}')"
-#if [ "$SQL_BUILD_RESULT" != "[success]" ]; then
-#  echo "ERROR: sql module package failed."
-#  # shellcheck disable=SC2242
-#  exit 1
-#fi
-#CONNECT_BUILD_RESULT="$(build/sbt clean connect-client-jvm/assembly | tail -n1 | awk '{print $1}')"
-#if [ "$CONNECT_BUILD_RESULT" != "[success]" ]; then
-#  echo "ERROR: connect-client-jvm module assembly failed."
-#  # shellcheck disable=SC2242
-#  exit 1
-#fi
+SQL_BUILD_RESULT="$(build/sbt clean sql/package | tail -n1 | awk '{print $1}')"
+if [ "$SQL_BUILD_RESULT" != "[success]" ]; then
+  echo "ERROR: sql module package failed."
+  # shellcheck disable=SC2242
+  exit 1
+fi
+CONNECT_BUILD_RESULT="$(build/sbt clean connect-client-jvm/assembly | tail -n1 | awk '{print $1}')"
+if [ "$CONNECT_BUILD_RESULT" != "[success]" ]; then
+  echo "ERROR: connect-client-jvm module assembly failed."
+  # shellcheck disable=SC2242
+  exit 1
+fi
 
-build/sbt clean sql/package
-build/sbt clean connect-client-jvm/assembly
 
 if [[ -x "$JAVA_HOME/bin/java" ]]; then
   JAVA_CMD="$JAVA_HOME/bin/java"
